[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.30.0"
rand = "0.8.5"
rsa = "0.9.6"
clap = { version = "4", features = ["derive"] }